FROM rootdbapp/rootdb-php-fpm:latest

# Arguments defined in docker-compose.yml
ARG user_id
ARG ROOTDB_RESET

ENV user=rootdb
ENV ROOTDB_RESET=$ROOTDB_RESET

# Install dev dependencies
RUN  install_packages git openssh-client vim

# Get latest Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Create system user to run Composer and Artisan Commands
RUN mkdir -p /home/$user/ \
    && mkdir -p /home/$user/.composer \
    && addgroup "$user" --gid "$user_id"\
    && adduser \
      --disabled-password \
      --gecos "" \
      --home "/home/$user" \
      --ingroup "$user" \
      --uid "$user_id" \
      "$user" \
    && mkdir /home/$user/.ssh \
    && chown -R $user:$user /home/$user

RUN mkdir /var/www/ \
    && mkdir /var/www/archives/ \
    && chown -R $user:$user /etc/supervisor* \
    && chown -R $user:$user /var/www \
    && chown -R $user:$user /home/$user/.ssh \
    && touch /var/log/php8.2-fpm.log \
    && chown $user:$user /var/log/php8.2-fpm.log

WORKDIR /var/www/archives/dev-git/api

USER $user

ENTRYPOINT [ "docker-entrypoint-dev.sh" ]

EXPOSE 9000

CMD ["php-fpm8.2", "-F"]
